### PR TITLE
Fix Gradle 7 deprecation warnings

### LINKED ISSUE #99: Warning about upcoming incompatibility with Gradle 7
Using the Plugin with Gradle 6 there are Warnings about an upcoming incompatibility with Gradle 7:
```
 ./gradlew --warning-mode all 

> Configure project :
The gatlingCompile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the gatlingImplementation configuration instead.
The gatlingRuntime configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the gatlingRuntimeOnly configuration instead.

[...]

BUILD SUCCESSFUL in 583ms
1 actionable task: 1 executed
```

### PR DESCRIPTION
**Pull request by marcphilipp**
Resolves #99.

### CODE REVIEW

**Comment by eshepelyuk** [comment]
@marcphilipp plz rebase PR squashing 3 commits into a single one
Plz use `feat`  as a commi type, comkit message should be taken from the #99 name, commit message should contain fix / reolve #99 

I am ready to merge since all tests are passing now

**Comment by eshepelyuk** [comment]
@marcphilipp my plan is to merge this PR, then update gatling version, if needed, and then create a new release, hopefully EoW :)

**Comment by marcphilipp** [comment]
> plz rebase PR squashing 3 commits into a single one

Will do. Did you know that you can use GitHub's "Squash and merge" to do just that, though?

**Comment by eshepelyuk** [comment]
> > plz rebase PR squashing 3 commits into a single one
> 
> Will do. Did you know that you can use GitHub's "Squash and merge" to do just that, though?

* Thnx
* yes I know

**Comment by eshepelyuk** [comment]
@marcphilipp thanks for the contribution, release is awaiting for #107 and #108 
hope both will be closed this week
join our gitter channel to receive new version announcements faster :)

**Pull request merged**
