### PR TITLE
Refactor plugin to use sourceSets for configuring Gatling sources and data

### PR DESCRIPTION
**Pull request by eshepelyuk**
### Summary

Basically this is WIP PR, since it doesn't contain proper tests but generally works.

List of changes
- `Gatling` simulations sources are configured using `Gradle `sourceSet
- simulation source and data directory structure is now fixed and uses `Maven` convention (i.e. `scala` and `resources` folder
- multiple `Gatling` simulations can be run during the build by the one task
- simulations can be included / excluded using build script configuration
- new task rule for running single simulation without modifying build script
- production and test sources are available for usage from `Gatling` simulations
- IDEA 2016 supports sources sets, so project using this plugin are properly configured after import
- migration to `Spock`
- possibility to run test directly from IDE
- showing `Gatling` progress output in while running functional tests

### Further possible Improvements
- update README
- create more robust test suite
- revive dedicated `gatling` task
- Continuous Integration using `TravisCI`

@lkishalmi waiting for your feedback to coordinate next steps regarding this refactoring.

### CODE REVIEW

**Comment by lkishalmi** [comment]
Huh, quite a beefy PR! Thank you!
I'm going to look through that during the weekend. Technically it was my intent not to use SourceSets and I tried to follow the folder structure like Gatling does.

I see the point and the value in your PR, I need some time to revalidate my own point of view. Depending on that I'm either fully accept your PR or try to modify it to let the two viewpoints live together side by side.

Once again, thank you for your contribution!

**Comment by eshepelyuk** [comment]
Well, sorry for misunderstanding about `sourceSet` usage.

I am really interested in improving this plugin since it looks like the most mature and alive on the market currently.
So, I am open for your feedback and ready to modify PR accordingly.

What I really would like to keep is
1. New functional tests using `Spock`
1. The way how simulations are looked for, i.e. using `Gradle` file tree filter
1. Adding production and test sources to `Gatling` classpath

**Comment by lkishalmi** [comment]
I'm sorry, I just had some time to look through the changes in detail.
I like the new functional tests with Spock and I have to admit that having sourceSets a great plus regarding IDE integration. 
Looking up simulations with Gradle tree filter was on my list as well, thanks for the implementation.
What I would change is the breaking of the compatibility quite in every bit with the previous version and following the changes in the README.md documentation.

In order to move the things forward I'm going to accept this PR now, without releasing a new plugin version. Then we need to implement a way to accept both Gatling style and Maven style directory layouts at least, do some documentation and maybe add a few samples.

**Comment by eshepelyuk** [comment]
Hello Laszlo @lkishalmi 

Thank you for accepting this contribution.

As a follow up - I've created new issue #7 that I'm going to work on.

Waiting for your feedback.

**Pull request merged**
