### PR TITLE
Gatling report

### PR DESCRIPTION
**Pull request by pedrogonzalezgutierrez**
In my company we are using this plugin and we are really happy because it works really good. Unfortunately we need a feature that doesn't support: Generate reports. We run our tests and collect the results in a single folder, then we run gatling with -ro option against that folder in order to generate the reports.

This pull request just add a new task (GatlingGenerateReportTask) that needs a parameter (the actual folder where the logs files are).

### CODE REVIEW

**Comment by eshepelyuk** [comment]
Have you looked into `$PROJECT_DIR/build/reports/gatling` ?
What's missing for you ?

**Comment by pedrogonzalezgutierrez** [comment]
We have different EC2 instances for different markets (CountryA, CountryB...) so we run the same test in different servers. We have a script that collect all the .log files of the simulations in a folder an then:
`./gatling.sh -ro <folderName>`
Which means [Generates the reports for the simulation log file located in](http://gatling.io/docs/2.2.3/general/configuration.html#command-line-options)
In this way we get the big picture of the behavior of the instances of our application.
Currently this plugin allow you to run a simulation and collect the results, this PR is about generate the reports when the simulations already finished.

**Comment by pedrogonzalezgutierrez** [comment]
The collecting script just copy the `simulation.log` files to the common folder appending the host name to the file name, actually:
`scp $USER_NAME@$HOST:$REMOTE_GATLING_REPORT_DIR/report/simulation.log $LOCAL_GATHER_REPORTS_DIR/simulation-$HOST.log`

**Comment by eshepelyuk** [comment]
Ok, I've understand your use case.
It differs from the issue I've discovered during analyzing your PR.
The issue is that while running multiple simulations via `gatlingRun` plugin generates separate HTML report for each simulation.
But this is smth not related to your PR, so nevermind :)                                                  

About the PR itself. I'd like to suggest some improvements to it

1. Make results directory a task parameter instead of passing it via system variable.                     24 1. It would be good if result directory will be declared as a `task input`, so `Gradle` could control if input files changed and consider task as UP-TO-DATE.
1. I don't think that the task should depend on `gatlingClasses`, since your task doesn't compile anythin    g and just generates HTML.
1. Please add some test cases, first you can take a look at existing functional tests.

**Comment by pedrogonzalezgutierrez** [comment]
I updated my pull request making the changes you suggested me, please let me know any concern.

I annotated the result directory property like `InputDirectory` (the [documentation](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/InputDirectory.html) says: _This will cause the task to be considered out-of-date when the directory location or contents have changed_) but it does not work. In my opinion is because every time I run the task the content of the directory changed (the report is generated there) so when I run again the task Gradle cant recognise it like UP-TO-DATE.

**Comment by pedrogonzalezgutierrez** [comment]
I updated the documentation as well.

**Comment by pedrogonzalezgutierrez** [comment]
Did you get the chance to review the PR?. If you want me to change something kindly revert. 
Awaiting your PR approval.

**Comment by eshepelyuk** [comment]
Sorry, on trips all this time. Yet had no time to review properly.

On Jan 19, 2017 12:38, "Pedro Gonzalez Gutierrez" <notifications@github.com>
wrote:

Did you get the chance to review the PR?. If you want me to change
something kindly revert.
Awaiting your PR approval.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/lkishalmi/gradle-gatling-plugin/pull/40#issuecomment-273754277>,
or mute the thread

**Pull request closed without merging**
